### ISSUE TITLE
Centered item names option missing? [1.12.2]

### ISSUE THREAD

**Issue by PolySaken-I-Am** [AHilyard/LegendaryTooltips#11]
The curseforge project page mentions the ability to center item names in the tooltip settings, but there is no such option in the in game config menu or in the config file. Running 1.12.2; I assume this is still being supported as it's the main version set on curseforge and the most recent file version.

**Comment by AHilyard** [comment]
Hi there, sorry title centering was added in Legendary Tooltips version 1.2, which is after the current version 1.1.6 that is supported on Minecraft 1.12.  Unfortunately this version of Minecraft is "limited support" (please see https://docs.google.com/spreadsheets/d/1eXCVvE6q1lJddwk75yRR8Z0MeNiLfriubC7iWd057yM/edit#gid=0), meaning I will only be fixing severe bugs and not adding new features.  This may change in the future depending on demand, but supporting so many versions with all the new features is not currently possible for me due to the amount of time and effort it takes.  Sorry about that.

**Comment by PolySaken-I-Am** [comment]
You should probably add that information to the curseforge page. When the 1.12.2 version is being actively updated people will assume it's fully supported unless informed otherwise.
