### ISSUE TITLE
Mod interaction, IllegalStateException: Tag used before it was bound

### ISSUE THREAD

**Issue by Dutchs** [AHilyard/LegendaryTooltips#13]
## Description
Crash when pressing shift while in keybind UI while a tooltip is visible, appears to be a mod interaction between Controlling, Legendary Tooltips and KubeJS 

## Crash Log
[crash-2022-02-05_17.41.25-client.txt](https://github.com/AHilyard/LegendaryTooltips/files/8008519/crash-2022-02-05_17.41.25-client.txt)

## Related Mods
Controlling-forge-1.18.1-9.0+14
LegendaryTooltips-1.18.1-1.2.2
Iceberg-1.18.1-1.0.40
kubejs-forge-1801.4.2-build.298
rhino-forge-1801.1.8-build.99
architectury-3.6.16

**Comment by Dutchs** [comment]
for additional context, this happens when in the main menu (not in-world), it appears to call com.anthonyhilyard.iceberg.util.ItemColor.getColorForItem which i suspect causes other mods down the line to error out because this is not expected.

**Comment by Dutchs** [comment]
Heres another related crashlog, that happens without KubeJS inside of the Catalogue Mods screen
[crash-2022-03-26_15.49.46-client.txt](https://github.com/AHilyard/LegendaryTooltips/files/8355711/crash-2022-03-26_15.49.46-client.txt)

**Comment by AHilyard** [comment]
Thank you for all the details, apologies for the delay on this.  I have been able to reproduce this issue on 1.18.1, but not on 1.18.2 versions (I know those didn't exist at the time of this issue).    I believe this is no longer a problem because of the new way tags are handled in 1.18.2, but please reopen this issue if it is still occurring for you on 1.18.2.
