### ISSUE TITLE
[Fabric] Install forgeconfigapiport, version 3.1 or later.

### ISSUE THREAD

**Issue by Miraurie** [AHilyard/LegendaryTooltips#14]
Hello, I'm using the Fabric version of the mod, when I run my game, I get the report that asks me to “Install forgeconfigapiport, version 3.1 or later.”. There's no info about where to get this, so I ask for help here. In my opinion, it shouldn't ask for a “Forge” Config when I play with Fabric…

**Comment by leok77** [comment]
It seems like that the fabric version of this mod needs https://www.curseforge.com/minecraft/mc-mods/forge-config-api-port-fabric as its front mod.

**Comment by AHilyard** [comment]
You are correct, Forge Config API Port is required to run the mod.  This mod provides the configuration functionality that the mod uses, and it is named because it is a port of the configuration system used in Forge, which is much more feature-rich than the previously-used configuration system (Cloth Config).  There is a link to it on the CurseForge mod page for Legendary Tooltips, or you can just use [this link](https://www.curseforge.com/minecraft/mc-mods/forge-config-api-port-fabric).
