### ISSUE TITLE
Always reload when try to play the game

### ISSUE THREAD

**Issue by Psychodeus** [AHilyard/LegendaryTooltips#42]
![image](https://user-images.githubusercontent.com/93028949/197324038-9b8b771b-659b-4aae-b774-0f1f951e1d2c.png)

https://user-images.githubusercontent.com/93028949/197324114-128ad126-d2cd-4bcb-afe4-a563c98fed63.mp4

When I isolate this trio mod, then I could load into the game. Not sure why.

Minecraft version: 1.19.2
Modloader: Fabric
Fabric loader version: 0.14.9

**Comment by AHilyard** [comment]
It's because you are using the 1.18.2 version of Prism.  Please use the 1.19.2 version to solve this.

**Comment by Psychodeus** [comment]
Why there is a lot of mod dependencies?

**Comment by AHilyard** [comment]
Iceberg provides events that Forge does not implement that are necessary to handle the custom tooltip behavior needed, which multiple mods rely on.  So for example, without Iceberg, comparison tooltips when you have both Equipment Compare and Legendary Tooltips wouldn't be able to be styled.  Additionally, I am also using its selector functionality to make the config file much more versatile when choosing items to apply borders to.  Prism is used for its color definitions functionality, which lets you have a wide variety of options when specifying border and background colors, as well as supporting animated colors.  It also provides the ability to have automatic border colors because the library can scan border images and pull out colors that match well.  Technically Prism could be made an optional dependency in a future version, however without it you would have very limited options and Eclectic Trove wouldn't work so I doubt the support headache would be worth it.  Iceberg is likely always going to be a required dependency as many mods use them provided events and I don't want to lose mod compatibility with Legendary Tooltips.
