### ISSUE TITLE
[1.19.2] Misaligned divider bar on custom bundles tooltip

### ISSUE THREAD

**Issue by Fuzss** [AHilyard/LegendaryTooltips#46]
Hi Grend, my [Easy Shulker Boxes](https://github.com/Fuzss/easyshulkerboxes) mod takes over rendering the item tooltip of bundles. All that works good and well, but only when the bundle is full your divider bar below the item name is misaligned. 

Any idea what could be causing this? Do you maybe do something custom for the bundle tooltip?

See here for screenshots: https://github.com/Fuzss/easyshulkerboxes/issues/13

**Comment by AHilyard** [comment]
Hey there, I believe the problem has to do with Forge's GatherComponents event.  Legendary Tooltips uses this event to calculate how many lines the tooltip's title will take up once the tooltip is rendered, thus knowing where to draw the separator line.
Normally these events will be fired off immediately prior to the tooltip being rendered, but (correct me if I am wrong) Easy Shulker Boxes is rendering a second tooltip as part of the rendering process of a component of the first, so where the title separator should be rendered is being calculated incorrectly.

That being said, my implementation is a bit more fragile than I realized.  I will try to get this fixed in the next update.

**Comment by AHilyard** [comment]
This has been fixed in version 1.4.0. 😄
