### ISSUE TITLE
Crashes when using Sodium 4.9+

### ISSUE THREAD

**Issue by Readf0x** [AHilyard/LegendaryTooltips#80]
Iceberg's custom `VertexConsumer` conflicts with sodium, which results in a crash.
[_sourced from jellysquid themself_](https://github.com/CaffeineMC/sodium-fabric/issues/1602#issuecomment-1421395700)
Mod version 1.4.3 on 1.19.4

[Crash report](https://pastebin.com/jThdjXxR)

Only current known fixes are:
- disable the 3D model in the tooltip via the config
- downgrade to sodium 4.8 or lower
- downgrade iceberg to 1.1.8 (compatible with sodium 4.10)

**Comment by AHilyard** [comment]
The version of Iceberg you are using has been archived due to this issue (it was made to be exclusively compatible with Sodium 0.4.11 which has been taken down). Please try version 1.1.9.1 (just released) with Sodium version 0.4.10.  Feel free to reopen this issue if this does not solve the problem.
